domwillcode/yale-smart-alarm-client

- setup.py
- yalesmartalarmclient/client.py
Slightly modification to @laf 's PR https://github.com/domwillcode/yale-smart-alarm-client/pull/3 (Thanks) to update to Yale's new API for home-assistant.io.
> Update new yale api

- yalesmartalarmclient/client.py
Added "DOOR_CONTACT" device functionality (could be window, etc.).
Includes constants for DOOR status and function to report latest status.
Assuming that this is accepted and published, I'll look into incorporating locks and doors into HA.
> Added get_doors_status()

- README.md
- yalesmartalarmclient/auth.py
- yalesmartalarmclient/client.py
- yalesmartalarmclient/lock.py
- authentication moved from the main client to a separate class
- Makes it easier to split client into multiple parts / apis.
Added functions to read locks and state and to manipulate state.
- Locks are created as a separate object
- A generator will give you the list of available locks. (I have just been able to test on 1 lock, since that is all i got)
If get or post requests get a timeout, a retry will silently happen instead of crashing script.
- made it simple by using a decorator.  Will try for 60 seconds before giving up.
- Kept the old function that is listing the locks and status, in case it is in use.
> merge locks and timeouts 

- README.md
- yalesmartalarmclient/client.py
Hi people of this repo,
I opened this issue #21 a while ago when I was looking for a way to trigger the alarm using HASS.
The help of these two guys ([@petheridge](https://github.com/qerim) [@qerim](https://github.com/petheridge)) pointed me in the right direction to understand how the API works, how to connect to it, and more important, how to trigger the alarm.
As a thank you, I have created added the panic button functionality to this client. Hope it helps somebody.
- These are the first lines of phyton I have written in my entire life
- I have not tested this code
> #21 Add panic button

- README.md
- setup.py
- yalesmartalarmclient/__init__.py
- yalesmartalarmclient/auth.py
- yalesmartalarmclient/client.py
Hi
Github version is not the same as published on pypi which we need to fix to take next steps getting the integration well functioning in HA.
Also backoff can not be an explicit version so modified == to >= to accomodate newer version.
Last but not least I added a few functions to get the full device and mode list out so it's easier to get the full json object back for various states (at least right now during dev).
Hope it can be approved and then uploaded to pypi shortly for version 3.3.
> New version required and modifications for next step with Home Assistant

- yalesmartalarmclient/auth.py
- yalesmartalarmclient/client.py
This PR should fix the issue discovered by @Mr-Grover  in https://github.com/domwillcode/yale-smart-alarm-client/issues/28
> #28: Fix for yapi/yapi after adding the panic button

- yalesmartalarmclient/auth.py
- yalesmartalarmclient/client.py
- yalesmartalarmclient/exceptions.py
- yalesmartalarmclient/lock.py
I did a small, perhaps cosmetic, cleanup of most of the code.
> Cosmetic and code-style cleanup

- yalesmartalarmclient/auth.py
Implement a broader exception into handling errors
> Implement broad exception

- yalesmartalarmclient/auth.py
> Add 403 to auth issue

- yalesmartalarmclient/auth.py
- yalesmartalarmclient/client.py
- yalesmartalarmclient/lock.py
> Fix deprecated typing

- yalesmartalarmclient/auth.py
> errors typing

- yalesmartalarmclient/auth.py
- yalesmartalarmclient/lock.py
> Introduce lock config methods

- yalesmartalarmclient/client.py
> Setup new list of locks

- yalesmartalarmclient/__init__.py
> Refactor init

- yalesmartalarmclient/client.py
Retrieve locks in their own function
> Move locks to own function

- package-lock.json
- package.json
- pyproject.toml
> Version 0.4.0

- package-lock.json
- package.json
- pyproject.toml
> Version 0.4.1

- yalesmartalarmclient/lock.py
> Handle when device has no minigw_lock_status

- package-lock.json
- package.json
- pyproject.toml
> Version 0.4.2

- yalesmartalarmclient/lock.py
Add configuration for lock to set config option for volume and autolock
> Add lock configuration

- package-lock.json
- package.json
- pyproject.toml
> Bump version to 0.4.3

- pyproject.toml
> Remove obsolete S320 rule
